import { scoreCandidature } from './scoring.js';
import { getCandidatures, saveCandidatures } from './storage.js';

function make(data) {
  const { score, scoreBreakdown } = scoreCandidature({
    langues:          data.langues,
    experienceRetail: data.experienceRetail,
    annéesExperience: data.annéesExperience,
    disponibilite:    data.disponibilite,
    niveauEtudes:     data.niveauEtudes,
    cv:               data.cv,
    dernierPoste:     data.dernierPoste     || '',
    dernierEmployeur: data.dernierEmployeur || '',
    secteurActivite:  data.secteurActivite  || '',
    diplomePrincipal: data.diplomePrincipal || '',
    adresse:          data.adresse          || '',
  });
  return { ...data, score, scoreBreakdown };
}

const MOCK = [
  make({
    id: 'mock_01', submittedAt: '2026-01-15T09:12:00.000Z', status: 'À contacter',
    nom: 'Benali', prenom: 'Fatima', email: 'fatima.benali@gmail.com', telephone: '+212 6 61 23 45 67',
    ville: 'Casablanca', adresse: 'Quartier Maarif',
    magasinSouhaite: 'Zara', posteRecherche: 'Conseiller(ère) de Vente',
    disponibilite: 'Immédiate',
    experienceRetail: 'oui', annéesExperience: '3 à 5 ans',
    dernierPoste: 'Conseillère de vente', dernierEmployeur: 'Zara Casablanca', secteurActivite: 'Retail mode',
    niveauEtudes: 'Bac+2', diplomePrincipal: 'BTS Commerce',
    langues: ['francais', 'arabe'],
    cv: { name: 'CV_Fatima_Benali.pdf', size: 245000 },
  }),
  make({
    id: 'mock_02', submittedAt: '2026-01-28T11:30:00.000Z', status: 'Retenu',
    nom: 'Oudrhiri', prenom: 'Mohammed', email: 'm.oudrhiri@outlook.com', telephone: '+212 6 62 34 56 78',
    ville: 'Casablanca', adresse: '',
    magasinSouhaite: 'Luxe', posteRecherche: 'Manager',
    disponibilite: 'Sous 1 mois',
    experienceRetail: 'oui', annéesExperience: 'Plus de 5 ans',
    dernierPoste: 'Superviseur boutique', dernierEmployeur: 'Louis Vuitton', secteurActivite: 'Luxe',
    niveauEtudes: 'Bac+5 et plus', diplomePrincipal: 'Master Commerce International',
    langues: ['francais', 'anglais', 'arabe'],
    cv: { name: 'CV_Mohammed_Oudrhiri.pdf', size: 312000 },
  }),
  make({
    id: 'mock_03', submittedAt: '2026-02-10T14:05:00.000Z', status: 'En cours',
    nom: 'Lahlou', prenom: 'Aïcha', email: 'aicha.lahlou@gmail.com', telephone: '+212 6 63 45 67 89',
    ville: 'Casablanca', adresse: 'Ain Sebaa',
    magasinSouhaite: 'Oysho', posteRecherche: 'Conseiller(ère) de Vente',
    disponibilite: 'Sous 15 jours',
    experienceRetail: 'oui', annéesExperience: '1 à 2 ans',
    dernierPoste: 'Vendeuse', dernierEmployeur: 'Oysho Marrakech', secteurActivite: 'Retail mode',
    niveauEtudes: 'Baccalauréat', diplomePrincipal: '',
    langues: ['francais', 'arabe'],
    cv: { name: 'CV_Aicha_Lahlou.pdf', size: 189000 },
  }),
  make({
    id: 'mock_04', submittedAt: '2026-02-20T10:20:00.000Z', status: 'À contacter',
    nom: 'Hajji', prenom: 'Youssef', email: 'youssef.hajji@hotmail.com', telephone: '+212 6 64 56 78 90',
    ville: 'Marrakech', adresse: '',
    magasinSouhaite: 'Bershka', posteRecherche: 'Conseiller(ère) de Vente',
    disponibilite: 'Immédiate',
    experienceRetail: 'oui', annéesExperience: "Moins d'1 an",
    dernierPoste: 'Vendeur', dernierEmployeur: 'Bershka Marrakech', secteurActivite: 'Retail',
    niveauEtudes: 'Bac+2', diplomePrincipal: 'DUT Vente',
    langues: ['francais', 'arabe'],
    cv: { name: 'CV_Youssef_Hajji.pdf', size: 156000 },
  }),
  make({
    id: 'mock_05', submittedAt: '2026-03-05T08:45:00.000Z', status: 'Retenu',
    nom: 'Tazi', prenom: 'Samira', email: 'samira.tazi@gmail.com', telephone: '+212 6 65 67 89 01',
    ville: 'Casablanca', adresse: 'Quartier Gauthier',
    magasinSouhaite: 'Luxe', posteRecherche: 'Conseiller(ère) de Vente',
    disponibilite: 'Immédiate',
    experienceRetail: 'oui', annéesExperience: '3 à 5 ans',
    dernierPoste: 'Conseillère clientèle luxe', dernierEmployeur: 'Cartier Casablanca', secteurActivite: 'Luxe',
    niveauEtudes: 'Bac+3', diplomePrincipal: 'Licence Commerce',
    langues: ['francais', 'anglais', 'espagnol', 'arabe'],
    cv: { name: 'CV_Samira_Tazi.pdf', size: 278000 },
  }),
  make({
    id: 'mock_06', submittedAt: '2026-03-18T16:00:00.000Z', status: 'En cours',
    nom: 'Bouchikhi', prenom: 'Omar', email: 'omar.bouchikhi@gmail.com', telephone: '+212 6 66 78 90 12',
    ville: 'Casablanca', adresse: '',
    magasinSouhaite: 'Massimo Dutti', posteRecherche: 'Directeur(trice) de Magasin',
    disponibilite: 'Sous 1 mois',
    experienceRetail: 'oui', annéesExperience: 'Plus de 5 ans',
    dernierPoste: 'Responsable boutique', dernierEmployeur: 'Mango Maroc', secteurActivite: 'Retail prêt-à-porter',
    niveauEtudes: 'Bac+5 et plus', diplomePrincipal: 'MBA Retail Management',
    langues: ['francais', 'anglais', 'arabe'],
    cv: { name: 'CV_Omar_Bouchikhi.pdf', size: 334000 },
  }),
  make({
    id: 'mock_07', submittedAt: '2026-04-02T09:30:00.000Z', status: 'À contacter',
    nom: 'Berrada', prenom: 'Nadia', email: 'nadia.berrada@yahoo.fr', telephone: '+212 6 67 89 01 23',
    ville: 'Marrakech', adresse: 'Guéliz',
    magasinSouhaite: 'Zara Home', posteRecherche: 'Conseiller(ère) de Vente',
    disponibilite: 'Sous 15 jours',
    experienceRetail: 'oui', annéesExperience: '1 à 2 ans',
    dernierPoste: 'Vendeuse décoration', dernierEmployeur: 'Zara Home Casablanca', secteurActivite: 'Retail décoration',
    niveauEtudes: 'Bac+2', diplomePrincipal: '',
    langues: ['francais', 'arabe'],
    cv: { name: 'CV_Nadia_Berrada.pdf', size: 210000 },
  }),
  make({
    id: 'mock_08', submittedAt: '2026-04-15T13:15:00.000Z', status: 'À contacter',
    nom: 'Senhaji', prenom: 'Khalid', email: 'k.senhaji@gmail.com', telephone: '+212 6 68 90 12 34',
    ville: 'Casablanca', adresse: 'Anfa',
    magasinSouhaite: 'Massimo Dutti', posteRecherche: 'Visual Merchandiser / Vitriniste',
    disponibilite: 'Sous 1 mois',
    experienceRetail: 'oui', annéesExperience: '3 à 5 ans',
    dernierPoste: 'Visual Merchandiser', dernierEmployeur: 'Massimo Dutti Maroc', secteurActivite: 'Retail mode',
    niveauEtudes: 'Bac+3', diplomePrincipal: 'Licence Arts Appliqués',
    langues: ['francais', 'anglais', 'arabe'],
    cv: { name: 'CV_Khalid_Senhaji.pdf', size: 265000 },
  }),
  make({
    id: 'mock_09', submittedAt: '2026-04-28T10:00:00.000Z', status: 'Retenu',
    nom: 'Filali', prenom: 'Houda', email: 'houda.filali@gmail.com', telephone: '+212 6 69 01 23 45',
    ville: 'Casablanca', adresse: 'Quartier Racine',
    magasinSouhaite: 'Luxe', posteRecherche: 'Manager',
    disponibilite: 'Immédiate',
    experienceRetail: 'oui', annéesExperience: 'Plus de 5 ans',
    dernierPoste: 'Senior Sales Advisor', dernierEmployeur: 'Chanel Paris', secteurActivite: 'Luxe',
    niveauEtudes: 'Bac+5 et plus', diplomePrincipal: 'Master Luxe & Retail',
    langues: ['francais', 'anglais', 'espagnol', 'arabe'],
    cv: { name: 'CV_Houda_Filali.pdf', size: 298000 },
  }),
  make({
    id: 'mock_10', submittedAt: '2026-05-03T15:20:00.000Z', status: 'Archivé',
    nom: 'Chaoui', prenom: 'Amine', email: 'amine.chaoui@gmail.com', telephone: '+212 6 60 12 34 56',
    ville: 'Marrakech', adresse: '',
    magasinSouhaite: 'Bershka', posteRecherche: 'Caissier(ère)',
    disponibilite: "Plus d'1 mois",
    experienceRetail: 'non', annéesExperience: '',
    dernierPoste: '', dernierEmployeur: '', secteurActivite: '',
    niveauEtudes: 'Baccalauréat', diplomePrincipal: '',
    langues: ['francais', 'arabe'],
    cv: null,
  }),
  make({
    id: 'mock_11', submittedAt: '2026-05-10T11:45:00.000Z', status: 'À contacter',
    nom: 'Kadiri', prenom: 'Zineb', email: 'zineb.kadiri@hotmail.com', telephone: '+212 6 61 23 45 60',
    ville: 'Rabat', adresse: 'Agdal',
    magasinSouhaite: 'Luxe', posteRecherche: 'Conseiller(ère) de Vente',
    disponibilite: 'Immédiate',
    experienceRetail: 'oui', annéesExperience: '3 à 5 ans',
    dernierPoste: 'Conseillère bijouterie', dernierEmployeur: 'Bvlgari Morocco Mall', secteurActivite: 'Luxe joaillerie',
    niveauEtudes: 'Bac+3', diplomePrincipal: 'Licence Gestion',
    langues: ['francais', 'anglais', 'arabe'],
    cv: { name: 'CV_Zineb_Kadiri.pdf', size: 241000 },
  }),
  make({
    id: 'mock_12', submittedAt: '2026-05-16T08:00:00.000Z', status: 'Archivé',
    nom: 'Bennani', prenom: 'Hassan', email: 'hassan.bennani@gmail.com', telephone: '+212 6 62 34 56 71',
    ville: 'Fès', adresse: '',
    magasinSouhaite: 'Pull & Bear', posteRecherche: 'Réserviste Stock',
    disponibilite: "Plus d'1 mois",
    experienceRetail: 'non', annéesExperience: '',
    dernierPoste: '', dernierEmployeur: '', secteurActivite: '',
    niveauEtudes: 'Baccalauréat', diplomePrincipal: '',
    langues: ['arabe'],
    cv: null,
  }),
  make({
    id: 'mock_13', submittedAt: '2026-05-22T14:30:00.000Z', status: 'Retenu',
    nom: 'Moussaoui', prenom: 'Leila', email: 'leila.moussaoui@gmail.com', telephone: '+212 6 63 45 67 82',
    ville: 'Marrakech', adresse: 'Hivernage',
    magasinSouhaite: 'Luxe', posteRecherche: 'Directeur(trice) de Magasin',
    disponibilite: 'Sous 1 mois',
    experienceRetail: 'oui', annéesExperience: 'Plus de 5 ans',
    dernierPoste: 'Responsable boutique LV', dernierEmployeur: 'Louis Vuitton Paris', secteurActivite: 'Luxe',
    niveauEtudes: 'Bac+5 et plus', diplomePrincipal: 'Master Luxe ESSEC',
    langues: ['francais', 'anglais', 'arabe'],
    cv: { name: 'CV_Leila_Moussaoui.pdf', size: 317000 },
  }),
  make({
    id: 'mock_14', submittedAt: '2026-05-28T09:00:00.000Z', status: 'En cours',
    nom: 'Alami', prenom: 'Rachid', email: 'r.alami@gmail.com', telephone: '+212 6 64 56 78 93',
    ville: 'Rabat', adresse: 'Hay Riad',
    magasinSouhaite: 'Massimo Dutti', posteRecherche: 'Visual Merchandiser / Vitriniste',
    disponibilite: 'Sous 15 jours',
    experienceRetail: 'oui', annéesExperience: '3 à 5 ans',
    dernierPoste: 'VM Coordinator', dernierEmployeur: 'Inditex Maroc', secteurActivite: 'Retail mode',
    niveauEtudes: 'Bac+3', diplomePrincipal: 'Licence Design',
    langues: ['francais', 'anglais', 'arabe'],
    cv: { name: 'CV_Rachid_Alami.pdf', size: 289000 },
  }),
  make({
    id: 'mock_15', submittedAt: '2026-06-01T10:30:00.000Z', status: 'À contacter',
    nom: 'Rifai', prenom: 'Sanae', email: 'sanae.rifai@gmail.com', telephone: '+212 6 65 67 89 04',
    ville: 'Casablanca', adresse: '',
    magasinSouhaite: 'Zara', posteRecherche: 'Conseiller(ère) de Vente',
    disponibilite: 'Immédiate',
    experienceRetail: 'oui', annéesExperience: '1 à 2 ans',
    dernierPoste: 'Vendeuse', dernierEmployeur: 'Zara Morocco Mall', secteurActivite: 'Retail mode',
    niveauEtudes: 'Bac+2', diplomePrincipal: 'BTS Vente',
    langues: ['francais', 'arabe'],
    cv: { name: 'CV_Sanae_Rifai.pdf', size: 178000 },
  }),
  make({
    id: 'mock_16', submittedAt: '2026-06-03T14:00:00.000Z', status: 'Retenu',
    nom: 'Mansouri', prenom: 'Tariq', email: 'tariq.mansouri@gmail.com', telephone: '+212 6 66 78 90 15',
    ville: 'Tanger', adresse: 'Centre-ville',
    magasinSouhaite: 'Luxe', posteRecherche: 'Manager',
    disponibilite: 'Sous 1 mois',
    experienceRetail: 'oui', annéesExperience: 'Plus de 5 ans',
    dernierPoste: 'Senior Advisor joaillerie', dernierEmployeur: 'Cartier Dubai', secteurActivite: 'Luxe joaillerie',
    niveauEtudes: 'Bac+5 et plus', diplomePrincipal: 'Master Commerce International',
    langues: ['francais', 'anglais', 'espagnol', 'arabe'],
    cv: { name: 'CV_Tariq_Mansouri.pdf', size: 356000 },
  }),
  make({
    id: 'mock_17', submittedAt: '2026-06-05T08:30:00.000Z', status: 'À contacter',
    nom: 'Chraibi', prenom: 'Imane', email: 'imane.chraibi@gmail.com', telephone: '+212 6 67 89 01 26',
    ville: 'Casablanca', adresse: '',
    magasinSouhaite: 'Oysho', posteRecherche: 'Caissier(ère)',
    disponibilite: 'Immédiate',
    experienceRetail: 'non', annéesExperience: '',
    dernierPoste: '', dernierEmployeur: '', secteurActivite: '',
    niveauEtudes: 'Bac+2', diplomePrincipal: 'BTS Marketing',
    langues: ['francais', 'arabe'],
    cv: { name: 'CV_Imane_Chraibi.pdf', size: 145000 },
  }),
  make({
    id: 'mock_18', submittedAt: '2026-06-07T11:00:00.000Z', status: 'En cours',
    nom: 'Ziani', prenom: 'Mehdi', email: 'mehdi.ziani@gmail.com', telephone: '+212 6 68 90 12 37',
    ville: 'Fès', adresse: '',
    magasinSouhaite: 'Massimo Dutti', posteRecherche: 'Réserviste Stock',
    disponibilite: 'Sous 15 jours',
    experienceRetail: 'oui', annéesExperience: "Moins d'1 an",
    dernierPoste: 'Manutentionnaire', dernierEmployeur: 'Entrepôt logistique', secteurActivite: 'Logistique',
    niveauEtudes: 'Baccalauréat', diplomePrincipal: '',
    langues: ['francais', 'arabe'],
    cv: { name: 'CV_Mehdi_Ziani.pdf', size: 198000 },
  }),
];

export function seedMockIfEmpty() {
  const existing = getCandidatures();
  if (existing.length === 0) saveCandidatures(MOCK);
}
