import { scoreCandidature } from './scoring.js';
import { getCandidatures, saveCandidatures } from './storage.js';

function make({ id, createdAt, nom, prenom, dateNaissance, email, telephone, ville,
  langues, magasinPrefere, mall, experience, poste, enseigne, cv, message, status }) {
  const { score, scoreBreakdown } = scoreCandidature({ langues, experience, cv, message });
  return { id, createdAt, nom, prenom, dateNaissance, email, telephone, ville,
    langues, magasinPrefere, mall, experience, poste, enseigne, cv, message,
    status, score, scoreBreakdown };
}

const MOCK = [
  make({ id:'mock_01', createdAt:'2026-01-15T09:12:00.000Z', nom:'Benali', prenom:'Fatima', dateNaissance:'1995-04-10', email:'fatima.benali@gmail.com', telephone:'+212 6 61 23 45 67', ville:'Casablanca', langues:['francais','arabe'], magasinPrefere:'Zara', mall:'Morocco Mall Casablanca', experience:'3 à 5 ans', poste:'Conseiller(e) de Vente', enseigne:'Zara', cv:{ name:'CV_Fatima_Benali.pdf', size:245000 }, message:'', status:'À contacter' }),
  make({ id:'mock_02', createdAt:'2026-01-28T11:30:00.000Z', nom:'Oudrhiri', prenom:'Mohammed', dateNaissance:'1988-08-22', email:'m.oudrhiri@outlook.com', telephone:'+212 6 62 34 56 78', ville:'Casablanca', langues:['francais','anglais','arabe'], magasinPrefere:'Louis Vuitton', mall:'Morocco Mall Casablanca', experience:'Plus de 5 ans', poste:'Superviseur(e) Boutique', enseigne:'Louis Vuitton', cv:{ name:'CV_Mohammed_Oudrhiri.pdf', size:312000 }, message:'Passionné par l\'univers du luxe avec 8 ans d\'expérience en maisons internationales.', status:'Retenu' }),
  make({ id:'mock_03', createdAt:'2026-02-10T14:05:00.000Z', nom:'Lahlou', prenom:'Aïcha', dateNaissance:'2002-11-03', email:'aicha.lahlou@gmail.com', telephone:'+212 6 63 45 67 89', ville:'Casablanca', langues:['francais'], magasinPrefere:'Oysho', mall:'Morocco Mall Casablanca', experience:'1 à 2 ans', poste:'Conseiller(e) de Vente', enseigne:'Oysho', cv:{ name:'CV_Aicha_Lahlou.pdf', size:189000 }, message:'', status:'En cours' }),
  make({ id:'mock_04', createdAt:'2026-02-20T10:20:00.000Z', nom:'Hajji', prenom:'Youssef', dateNaissance:'2000-06-15', email:'youssef.hajji@hotmail.com', telephone:'+212 6 64 56 78 90', ville:'Marrakech', langues:['francais','arabe'], magasinPrefere:'Bershka', mall:'Morocco Mall Marrakech', experience:"Moins d'1 an", poste:'Conseiller(e) de Vente', enseigne:'Bershka', cv:{ name:'CV_Youssef_Hajji.pdf', size:156000 }, message:'', status:'À contacter' }),
  make({ id:'mock_05', createdAt:'2026-03-05T08:45:00.000Z', nom:'Tazi', prenom:'Samira', dateNaissance:'1990-02-28', email:'samira.tazi@gmail.com', telephone:'+212 6 65 67 89 01', ville:'Casablanca', langues:['francais','anglais','espagnol'], magasinPrefere:'Cartier', mall:'Morocco Mall Casablanca', experience:'3 à 5 ans', poste:'Conseiller(e) Client Luxe', enseigne:'Cartier', cv:{ name:'CV_Samira_Tazi.pdf', size:278000 }, message:'Forte expérience en clientèle haut de gamme et trilingue.', status:'Retenu' }),
  make({ id:'mock_06', createdAt:'2026-03-18T16:00:00.000Z', nom:'Bouchikhi', prenom:'Omar', dateNaissance:'1985-09-14', email:'omar.bouchikhi@gmail.com', telephone:'+212 6 66 78 90 12', ville:'Casablanca', langues:['francais','anglais'], magasinPrefere:'Mango', mall:'Morocco Mall Casablanca', experience:'Plus de 5 ans', poste:'Responsable de Boutique', enseigne:'Mango', cv:{ name:'CV_Omar_Bouchikhi.pdf', size:334000 }, message:'10 ans dans le retail prêt-à-porter, je cherche un nouveau défi managérial.', status:'En cours' }),
  make({ id:'mock_07', createdAt:'2026-04-02T09:30:00.000Z', nom:'Berrada', prenom:'Nadia', dateNaissance:'1998-12-07', email:'nadia.berrada@yahoo.fr', telephone:'+212 6 67 89 01 23', ville:'Marrakech', langues:['francais','arabe'], magasinPrefere:'Zara Home', mall:'Morocco Mall Marrakech', experience:'1 à 2 ans', poste:'Conseiller(e) de Vente', enseigne:'Zara Home', cv:{ name:'CV_Nadia_Berrada.pdf', size:210000 }, message:'', status:'À contacter' }),
  make({ id:'mock_08', createdAt:'2026-04-15T13:15:00.000Z', nom:'Senhaji', prenom:'Khalid', dateNaissance:'1993-05-19', email:'k.senhaji@gmail.com', telephone:'+212 6 68 90 12 34', ville:'Casablanca', langues:['francais','anglais'], magasinPrefere:'Massimo Dutti', mall:'Morocco Mall Casablanca', experience:'3 à 5 ans', poste:'Visual Merchandiser', enseigne:'Massimo Dutti', cv:{ name:'CV_Khalid_Senhaji.pdf', size:265000 }, message:'', status:'À contacter' }),
  make({ id:'mock_09', createdAt:'2026-04-28T10:00:00.000Z', nom:'Filali', prenom:'Houda', dateNaissance:'1987-03-30', email:'houda.filali@gmail.com', telephone:'+212 6 69 01 23 45', ville:'Casablanca', langues:['francais','anglais','espagnol'], magasinPrefere:'Chanel', mall:'Morocco Mall Casablanca', experience:'Plus de 5 ans', poste:'Conseiller(e) de Vente Senior', enseigne:'Chanel', cv:{ name:'CV_Houda_Filali.pdf', size:298000 }, message:'Expert en maisons de luxe, maîtrise parfaite de 3 langues.', status:'Retenu' }),
  make({ id:'mock_10', createdAt:'2026-05-03T15:20:00.000Z', nom:'Chaoui', prenom:'Amine', dateNaissance:'2003-07-08', email:'amine.chaoui@gmail.com', telephone:'+212 6 60 12 34 56', ville:'Marrakech', langues:['francais'], magasinPrefere:'Stradivarius', mall:'Morocco Mall Marrakech', experience:"Moins d'1 an", poste:'', enseigne:'', cv:null, message:'', status:'Archivé' }),
  make({ id:'mock_11', createdAt:'2026-05-10T11:45:00.000Z', nom:'Kadiri', prenom:'Zineb', dateNaissance:'1992-10-25', email:'zineb.kadiri@hotmail.com', telephone:'+212 6 61 23 45 60', ville:'Rabat', langues:['francais','anglais'], magasinPrefere:'Bvlgari', mall:'Morocco Mall Casablanca', experience:'3 à 5 ans', poste:'Conseiller(e) Client Luxe', enseigne:'Bvlgari', cv:{ name:'CV_Zineb_Kadiri.pdf', size:241000 }, message:'', status:'À contacter' }),
  make({ id:'mock_12', createdAt:'2026-05-16T08:00:00.000Z', nom:'Bennani', prenom:'Hassan', dateNaissance:'1978-01-11', email:'hassan.bennani@gmail.com', telephone:'+212 6 62 34 56 71', ville:'Fès', langues:['arabe'], magasinPrefere:'Pull & Bear', mall:'Morocco Mall Casablanca', experience:'Aucune expérience', poste:'', enseigne:'', cv:null, message:'', status:'Archivé' }),
  make({ id:'mock_13', createdAt:'2026-05-22T14:30:00.000Z', nom:'Moussaoui', prenom:'Leila', dateNaissance:'1983-06-16', email:'leila.moussaoui@gmail.com', telephone:'+212 6 63 45 67 82', ville:'Marrakech', langues:['francais','anglais'], magasinPrefere:'Louis Vuitton', mall:'Morocco Mall Marrakech', experience:'Plus de 5 ans', poste:'Superviseur(e) Boutique', enseigne:'Louis Vuitton', cv:{ name:'CV_Leila_Moussaoui.pdf', size:317000 }, message:'Ancienne responsable boutique LV Paris, de retour au Maroc.', status:'Retenu' }),
  make({ id:'mock_14', createdAt:'2026-05-28T09:00:00.000Z', nom:'Alami', prenom:'Rachid', dateNaissance:'1986-04-02', email:'r.alami@groupeaksal.com', telephone:'+212 6 64 56 78 93', ville:'Rabat', langues:['francais','anglais'], magasinPrefere:'Groupe AKSAL', mall:'Siège Social', experience:'3 à 5 ans', poste:'Stagiaire Marketing Digital', enseigne:'Groupe AKSAL', cv:{ name:'CV_Rachid_Alami.pdf', size:289000 }, message:'Intéressé par un poste support au siège, avec vision cross-marques.', status:'En cours' }),
  make({ id:'mock_15', createdAt:'2026-06-01T10:30:00.000Z', nom:'Rifai', prenom:'Sanae', dateNaissance:'2001-08-20', email:'sanae.rifai@gmail.com', telephone:'+212 6 65 67 89 04', ville:'Casablanca', langues:['francais','arabe'], magasinPrefere:'Zara', mall:'Morocco Mall Casablanca', experience:'1 à 2 ans', poste:'Conseiller(e) de Vente', enseigne:'Zara', cv:{ name:'CV_Sanae_Rifai.pdf', size:178000 }, message:'', status:'À contacter' }),
  make({ id:'mock_16', createdAt:'2026-06-03T14:00:00.000Z', nom:'Mansouri', prenom:'Tariq', dateNaissance:'1980-12-05', email:'tariq.mansouri@gmail.com', telephone:'+212 6 66 78 90 15', ville:'Tanger', langues:['francais','anglais','espagnol'], magasinPrefere:'Cartier', mall:'Morocco Mall Marrakech', experience:'Plus de 5 ans', poste:'Conseiller(e) Client Luxe', enseigne:'Cartier', cv:{ name:'CV_Tariq_Mansouri.pdf', size:356000 }, message:'15 ans en joaillerie de luxe entre Paris et Dubai.', status:'Retenu' }),
  make({ id:'mock_17', createdAt:'2026-06-05T08:30:00.000Z', nom:'Chraibi', prenom:'Imane', dateNaissance:'2004-03-17', email:'imane.chraibi@gmail.com', telephone:'+212 6 67 89 01 26', ville:'Casablanca', langues:['francais'], magasinPrefere:'Oysho', mall:'Morocco Mall Casablanca', experience:'Aucune expérience', poste:'Conseiller(e) de Vente', enseigne:'Oysho', cv:{ name:'CV_Imane_Chraibi.pdf', size:145000 }, message:'Récente diplômée, très motivée pour débuter dans le retail mode.', status:'À contacter' }),
  make({ id:'mock_18', createdAt:'2026-06-07T11:00:00.000Z', nom:'Ziani', prenom:'Mehdi', dateNaissance:'1999-09-28', email:'mehdi.ziani@gmail.com', telephone:'+212 6 68 90 12 37', ville:'Fès', langues:['francais','arabe'], magasinPrefere:'Mango', mall:'Siège Social', experience:"Moins d'1 an", poste:'', enseigne:'', cv:{ name:'CV_Mehdi_Ziani.pdf', size:198000 }, message:'', status:'En cours' }),
];

export function seedMockIfEmpty() {
  const existing = getCandidatures();
  if (existing.length === 0) saveCandidatures(MOCK);
}
